In [91]:
import numpy as np
import pandas as pd

# Exercise 1

In [92]:
# creating numpy array from 1 to 10, then reshaping into 2X5 matrix
array = np.arange(1,11)
reshape = array.reshape(2, 5)
print("array before reshaping:")
print(array)
print("array after reshaping(after creating matrix):")
reshape

array before reshaping:
[ 1  2  3  4  5  6  7  8  9 10]
array after reshaping(after creating matrix):


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Exercise 2

In [93]:
# creating numpy arrays from 1 to 20 and extracting numbers between 5th and 15 th index
array_2 = np.arange(1, 21)
print(array_2)

elements_extracted = array_2[5:16]
print("Output after Extraction:")
print(elements_extracted)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Output after Extraction:
[ 6  7  8  9 10 11 12 13 14 15 16]


# Excercise 3

In [94]:
# creating a panda series  
fruits = pd.Series ({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits               

apples     3
bananas    2
oranges    1
dtype: int64

In [95]:
#adding a new item
fruits['pears'] = 4
print("Output:")
print(fruits) 

Output:
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# Excercise 4

In [96]:
# creating a dataframe with columns name,age,gender(10 raws of data)

data = {
    'name': ['Saniya','Sony','Manju','Radha','Sunil','Mini','Sarika','Bindhu','Munni','Annie'],
    'age' : [34,32,23,24,31,25,19,33,27,35],
    'gender':['Female', 'Male', 'Female','Female','Male','Female','Female','Female','Female','Female']
}
df = pd.DataFrame(data)
print(df)

     name  age  gender
0  Saniya   34  Female
1    Sony   32    Male
2   Manju   23  Female
3   Radha   24  Female
4   Sunil   31    Male
5    Mini   25  Female
6  Sarika   19  Female
7  Bindhu   33  Female
8   Munni   27  Female
9   Annie   35  Female


# Exercise 5

In [97]:
# adding a new column called occupation
df['occupation'] = ['Programmer', 'Manager', 'Analyst','Manager','Manager', 'Analyst','Programmer','Programmer', 'Manager', 'Analyst']
print("Output:")
print(df)

Output:
     name  age  gender  occupation
0  Saniya   34  Female  Programmer
1    Sony   32    Male     Manager
2   Manju   23  Female     Analyst
3   Radha   24  Female     Manager
4   Sunil   31    Male     Manager
5    Mini   25  Female     Analyst
6  Sarika   19  Female  Programmer
7  Bindhu   33  Female  Programmer
8   Munni   27  Female     Manager
9   Annie   35  Female     Analyst


# Exercise 6

In [98]:
# selecting the rows of the d.frame where the age>=30
Age_selected = df[df['age'] >= 30]
print("Output:")
print(Age_selected)

Output:
     name  age  gender  occupation
0  Saniya   34  Female  Programmer
1    Sony   32    Male     Manager
4   Sunil   31    Male     Manager
7  Bindhu   33  Female  Programmer
9   Annie   35  Female     Analyst


# Exercise 7

In [99]:
#  Converting this d.frame to a csv file and read that csv file, finally display the contents. 
df.to_csv("dataframe_csv", index = False)
df_read_file = pd.read_csv("dataframe_csv")
print("Output:")
print(df_read_file)

Output:
     name  age  gender  occupation
0  Saniya   34  Female  Programmer
1    Sony   32    Male     Manager
2   Manju   23  Female     Analyst
3   Radha   24  Female     Manager
4   Sunil   31    Male     Manager
5    Mini   25  Female     Analyst
6  Sarika   19  Female  Programmer
7  Bindhu   33  Female  Programmer
8   Munni   27  Female     Manager
9   Annie   35  Female     Analyst
